//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO_ESPECIFICO
    {
        public string codigo { get; set; }
        public string conducta { get; set; }
        public System.DateTime? fecha_inicio { get; set; }
        public System.DateTime? fecha_final { get; set; }
        public string estado { get; set; }
        public string codigo_retiro_temporal { get; set; }
        public string codigo_inmovilizacion { get; set; }
        public string observacion_noaplicacion { get; set; }
    }
}
