//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoridad
    {
        public string Id { get; set; }
        public string Descripcion { get; set; }
        public int CodigoOpcionFormulario { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeFin { get; set; }

        public string DescripcionCodigoOpcionFormulario
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                {
                    OpcionDeFormulario opcionDeFormulario = db.OPCIONFORMULARIO.Find(CodigoOpcionFormulario);
                    if (opcionDeFormulario.Id == CodigoOpcionFormulario)
                    {
                        return Descripcion = opcionDeFormulario.Descripcion;
                    }
                }
                return Descripcion;
            }
        }

    }
}

