//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraSIBOAC
    {
        public long Id { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string NombreTabla { get; set; }
        public string CodigoUsuario { get; set; }
        public string Operacion { get; set; }
        public string ValorAntes { get; set; }
        public string ValorDespues { get; set; }
    }
}
