//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CatalogoDeArticulos
    {
        [DisplayName("Código")]
        [Required(ErrorMessage = "El código es obligatorio")]
        [StringLength(6, ErrorMessage = "El codigo no debe ser mayor a 6 caracteres.")]
        public string Id { get; set; }

        [DisplayName("Conducta")]
        [Required(ErrorMessage = "La conducta es obligatoria")]
        [StringLength(2, ErrorMessage = "La conducta no debe ser mayor a 2 caracteres.")]
        public string Conducta { get; set; }

        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de inicio")]
        [Required(ErrorMessage = "La fecha de inicio es obligatoria")]
        public System.DateTime FechaDeInicio { get; set; }

        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de fin")]
        [Required(ErrorMessage = "La fecha de fin es obligatoria")]
        public System.DateTime FechaDeFin { get; set; }

        [DisplayName("Descripción")]
        [StringLength(255, ErrorMessage = "La descripción no debe ser mayor a 255 caracteres")]
        [Required(ErrorMessage = "La descripción es obligatoria")]
        public string Descripcion { get; set; }

        [DisplayName("Monto de la multa")]
        [Required(ErrorMessage = "El monto es obligatorio")]
        //[Range(0.01, 999999999.99, ErrorMessage = "El precio solo puede tener 2 decimales 0.00")]
        //[DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"^[0-9]+(\,[0-9]{1,2})?$", ErrorMessage = "La multa solo puede tener 2 decimales 0.00")]
        //[Range(0, 9999999999999999.99)]
        //[DataType(DataType.Currency, ErrorMessage = "El valor ingresado no es un monto valido")]
        public decimal Multa
        {
            get
            {
                multa = decimal.Round(multa, 2);
                return multa;
            }
            set
            {
                multa = value;
            }
        }
        private decimal multa { get; set; }

        [StringLength(1, ErrorMessage = "El estado no debe ser mayor a 1 caracter.")]
        [DisplayName("Estado")]
        [Required(ErrorMessage = "El estado es obligatorio")]
        public string Estado { get; set; }

        [DisplayName("Puntos")]
        [Required(ErrorMessage = "Los puntos son obligatorios")]
        public int Puntos { get; set; }

        [DisplayName("Totalidad")]
        [Required(ErrorMessage = "La totalidad es obligatoria")]
        public int Totalidad { get; set; }
    }
}
