//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CodigoDeLaPlaca
    {

        [DisplayName("Codigo")]
        [StringLength(3, ErrorMessage = "El código no debe ser mayor a 3 caracteres")]
        [Required(ErrorMessage = "El codigo es obligatorio")]
        public string Id { get; set; }


        [DisplayName("Estado")]
        [StringLength(10, ErrorMessage = "El estado no debe ser mayor a 1 caracter")]
        public string Estado { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de inicio")] //etiqueta Fecha de inicio
        public Nullable<System.DateTime> FechaDeInicio { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de fin")] //etiqueta Fecha de fin
        public Nullable<System.DateTime> FechaDeFin { get; set; }
    }
}
