//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispositivoPorRolPersona
    {
        public string CodigoRolPersona { get; set; }
        public int CodigoDispositivo { get; set; }


        public string DescripcionRolPersona
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                {
                    RolPorPersona rolPorPersona = db.ROLPERSONA.Find(CodigoRolPersona);
                    if (rolPorPersona.Id == CodigoRolPersona)
                    {
                        return Descripcion = rolPorPersona.Descripcion;
                    }
                }
                return Descripcion;
            }
        }

        public string DescripcionDispositivo
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                {
                    Dispositivo dispositivo = db.Dispositivoes1.Find(CodigoDispositivo);
                    if (dispositivo.Id == CodigoDispositivo)
                    {
                        return Descripcion = dispositivo.Descripcion;
                    }
                }
                return Descripcion;
            }
        }

    }
}
