//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public int IdCanton { get; set; }
        public string CodigoOficinaImpugna { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public System.DateTime FechaDeFin { get; set; }

        public string DescripcionCanton
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                Canton canton = db.CANTON.Find(IdCanton);
                if (canton.Id == IdCanton)
                {
                     return Descripcion = canton.Descripcion;
                }
              
                return Descripcion;
            }
        }

        public string DescripcionOficina
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                OficinaParaImpugnar oficina = db.OficinaParaImpugnars.Find(CodigoOficinaImpugna);
                if (oficina.Id == CodigoOficinaImpugna)
                {
                    return Descripcion = oficina.Descripcion;
                }

                return Descripcion;
            }
        }

    }
}
