//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edad
    {
        public System.DateTime FechaMinNacimiento { get; set; }
        public System.DateTime FechaMaxNacimiento { get; set; }
        public System.DateTime FechaPorDefecto { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeFin { get; set; }
    }
}
