
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cosevi.SIBOAC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExamenNivelAlcohol
{

    public int codexa { get; set; }

    public string descripcion { get; set; }

    public Nullable<double> alcmin_aire { get; set; }

    public Nullable<double> alcmax_aire { get; set; }

    public Nullable<double> alcmin_sangre { get; set; }

    public Nullable<double> alcmax_sangre { get; set; }

    public Nullable<int> tipo_conductor { get; set; }

    public string articulo_sugerido { get; set; }

    public string estado { get; set; }

    public Nullable<System.DateTime> fecha_inicio { get; set; }

    public Nullable<System.DateTime> fecha_fin { get; set; }

}

}
