//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERALES
    {
        public string Inspector { get; set; }
        public long ConsecutivoBC { get; set; }
        public Nullable<long> ConsecutivoPO { get; set; }
        public string HandHeld { get; set; }
        public int Copias { get; set; }
        public string Piepagina { get; set; }
        public string ClaveIns { get; set; }
        public string ClaveAdmin { get; set; }
        public Nullable<int> Serie { get; set; }
        public Nullable<long> ConsecutivoSinDoc { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string ConsecutivoNumeroMarco { get; set; }
        public Nullable<bool> PasswordActualizado { get; set; }
    }
}
