
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cosevi.SIBOAC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class IMAGENES
{

    public string Fuente { get; set; }

    public int Serie { get; set; }

    public string Numero { get; set; }

    public string Tipo { get; set; }

    public byte[] Imagen { get; set; }

    public string Identificacion { get; set; }

    public string tipo_ide { get; set; }

    public Nullable<System.DateTime> fechaRegistro { get; set; }

}

}
