//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Inconsistencia
    {
        [DisplayName("Código")]
        [Required(ErrorMessage = "El código es obligatorio")]
        public short Id { get; set; }


        [DisplayName("Descripción")]
        [StringLength(50, ErrorMessage = "La descripción no debe ser mayor a 50 caracteres")]
        [Required(ErrorMessage = "La descripción es obligatoria")]
        public string Descripcion { get; set; }
    }
}
