//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LEYENDAPORAUTORIDAD
    {
        [DisplayName("Autoridad Judicial")]
        [Required(ErrorMessage = "La autoridad es obligatorio")]
        public string IdAutoridad { get; set; }

        [DisplayName("Pie de Página")]
        [Required(ErrorMessage = "El pie de página es obligatorio")]
        public string PiePagina { get; set; }

        [DisplayName("Estado")]
        [Required(ErrorMessage = "El estado es obligatorio")]
        public string Estado { get; set; }

        [DisplayName("Fecha de inicio")]
        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "La fecha de inicio es obligatoria")]
        public System.DateTime Fecha_Inicio { get; set; }

        [DisplayName("Fecha de fin")]
        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "La fecha de fin es obligatoria")]
        public System.DateTime Fecha_Fin { get; set; }

        [DisplayName("Descripción")]
      
        public string DescripcionAutoridad { get; set; }
    }
}
