//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoPorNoFirmar
    {
        [DisplayName("Código")]
        [StringLength(2, ErrorMessage = "El código no debe ser mayor a 2 caracteres.")]
        public string Id { get; set; }
        [DisplayName("Descripción")]
        [StringLength(50, ErrorMessage = "La descripción no debe ser mayor a 50 caracteres.")]
        public string Descripcion { get; set; }
        [StringLength(1, ErrorMessage = "El estado no debe ser mayor a 1 caracter.")]
        public string Estado { get; set; }
        [DisplayName("Fecha de inicio")]
        [Required(ErrorMessage = "La fecha de inicio es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaDeInicio { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaDeFin { get; set; }
    }
}
