//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Nacionalidad
    {
        [DisplayName("Código")]
        [Required(ErrorMessage = "El código es obligatorio")]
        [StringLength(3, ErrorMessage = "El código no debe ser mayor a 3 caracteres.")]
        public string Id { get; set; }

        [DisplayName("Descripción")]
        [StringLength(50, ErrorMessage = "La descripción no debe ser mayor a 50 caracteres.")]
        [Required(ErrorMessage = "La descripción es obligatoria")]
        public string Descripcion { get; set; }

        [DisplayName("Estado")]
        [Required(ErrorMessage = "El estado es obligatorio")]
        [StringLength(1, ErrorMessage = "El estado no debe ser mayor a 1 caracter.")]
        public string Estado { get; set; }

        [DisplayName("Fecha de inicio")]
        [Required(ErrorMessage = "La fecha de inicio es obligatoria.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaDeInicio { get; set; }

        [DisplayName("Fecha de fin")]
        [Required(ErrorMessage = "La fecha de fin es obligatoria.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaDeFin { get; set; }

        [DisplayName("Prioridad")]
        [Required(ErrorMessage = "La descripción es obligatoria")]
        public Nullable<int> Prioridad { get; set; }
    }
}
