//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OficinaParaImpugnar
    {
        [DisplayName("Código")]
        public string Id { get; set; }
        [DisplayName("Nombre de Oficina")]
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        [DisplayName("Fecha de Inicio")]
        public Nullable<System.DateTime> FechaDeInicio { get; set; }
        [DisplayName("Fecha de Fin")]
        public Nullable<System.DateTime> FechaDeFin { get; set; }
    }
}
