//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtrosAdjuntos
    {
        public string fuente { get; set; }
        public int serie { get; set; }
        public decimal numero { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string extension { get; set; }
        public Nullable<int> consecutivo_extension { get; set; }
        public string linkArchivo { get; set; }
    }
}
