//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteOficial
    {
        public string Fuente { get; set; }
        public string Serie { get; set; }
        public string NumeroParte { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Kilometro { get; set; }
        public Nullable<int> Seccion { get; set; }
        public Nullable<int> CodUbi { get; set; }
        public string Direccion { get; set; }
        public int Velocidad { get; set; }
        public int CodEst { get; set; }
        public int CodTCal { get; set; }
        public int CodCCal { get; set; }
        public int CodECal { get; set; }
        public int CodIlu { get; set; }
        public int CodTie { get; set; }
        public int Vertical { get; set; }
        public int horizontal { get; set; }
        public int CodInt { get; set; }
        public int CodAcc { get; set; }
        public int CodCir { get; set; }
        public int CodObs { get; set; }
        public int CodPea { get; set; }
        public string called { get; set; }
        public string callea { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string calle1 { get; set; }
        public string avenida1 { get; set; }
        public string avenida2 { get; set; }
        public string codsen { get; set; }
        public string codcarril { get; set; }
        public byte[] croquis { get; set; }
        public byte[] firma_inspector { get; set; }
        public Nullable<System.DateTime> fecha_descarga { get; set; }
        public Nullable<int> numeroHH { get; set; }
        public Nullable<System.DateTime> fechaexportacionHH { get; set; }
        public Nullable<bool> Impresion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> plano_generado { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string usuario_entregaPlano { get; set; }
        public Nullable<short> StatusPlano { get; set; }
        public Nullable<bool> entrega_corte { get; set; }
        public Nullable<System.DateTime> fecha_entregacorte { get; set; }
        public string usuario_entregacorte { get; set; }
        public Nullable<bool> AmbienteEnCampo { get; set; }
    }
}
