//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RutasPorDistritos
    {
        [DisplayName("Código del distrito")]
        [Required(ErrorMessage = "El código es obligatorio")]
        public int CodigoDistrito { get; set; }

        [DisplayName("Código de la ruta")]
        [Required(ErrorMessage = "El código es obligatorio")]
        public int CodigoRuta { get; set; }

        [DisplayName("Kilometros")]
        [Required(ErrorMessage = "Los kilometros son obligatorios")]
        public int Km { get; set; }

        [DisplayName("Estado")]
        [StringLength(1, ErrorMessage = "El estado no debe ser mayor a 1 caracter.")]
        [Required(ErrorMessage = "El estado es obligatorio")]
        public string Estado { get; set; }

        [DisplayName("Fecha de inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "La fecha de inicio es obligatoria")]
        public Nullable<System.DateTime> FechaDeInicio { get; set; }

        [DisplayName("Fecha de fin")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "La fecha de fin es obligatoria")]
        public Nullable<System.DateTime> FechaDeFin { get; set; }

        public string DescripcionDistrito
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                {
                    Distrito distrito = db.DISTRITO.Find(CodigoDistrito);
                    if (distrito.Id == CodigoDistrito)
                    {
                        return Descripcion = distrito.Descripcion;
                    }
                }
                return Descripcion;
            }
        }

        public string DescripcionRuta
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                {
                    Ruta ruta = db.Ruta.Find(CodigoRuta);
                    if (ruta.Id == CodigoRuta)
                    {
                        return Descripcion = ruta.Inicia  + " - " + ruta.Termina ;
                    }
                }
                return Descripcion;
            }
        }

    }
}
