//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Sexo
    {
        [DisplayName("Código")]
        [StringLength(1, ErrorMessage = "El código no debe ser mayor a 1 caracter")]
        [Required(ErrorMessage = "El código es obligatorio")]
        public string Id { get; set; }

        [DisplayName("Descripción")]
        [StringLength(10, ErrorMessage = "La descripción no debe ser mayor a 10 caracteres")]
        [Required(ErrorMessage = "La descripción es obligatoria")]
        public string Descripcion { get; set; }

        [StringLength(1, ErrorMessage = "El estado no debe ser mayor a 1 caracter.")]
        [Required(ErrorMessage = "El estado es obligatorio")]
        [DisplayName("Estado")]
        public string Estado { get; set; }


        [DataType(DataType.Date)]
        [Required(ErrorMessage = "La fehca de inicio es obligatoria")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de inicio")] //etiqueta Fecha de inicio
        public System.DateTime FechaDeInicio { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "La fehca de fin es obligatoria")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de fin")] //etiqueta Fecha de fin
        public System.DateTime FechaDeFin { get; set; }
    }
}
