//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIBOACMenuOpciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIBOACMenuOpciones()
        {
            this.SIBOACRoles = new HashSet<SIBOACRoles>();
        }
    
        public int MenuOpcionesID { get; set; }
        public string Descripcion { get; set; }
        public string URL { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIBOACRoles> SIBOACRoles { get; set; }
    }
}
