//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIBOACSecurityEntities : DbContext
    {
        public SIBOACSecurityEntities()
            : base("name=SIBOACSecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SIBOACUsuarios> SIBOACUsuarios { get; set; }
        public virtual DbSet<SIBOACRoles> SIBOACRoles { get; set; }
        public virtual DbSet<SIBOACMenuOpciones> SIBOACMenuOpciones { get; set; }
        public virtual DbSet<SIBOACTablas> SIBOACTablas { get; set; }
    }
}
