//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTIGO
    {
        public string tipo_ide { get; set; }
        public string identificacion { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string firma_testigo { get; set; }
        public string fuente { get; set; }
        public int serie { get; set; }
        public decimal numero { get; set; }
    }
}
