
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cosevi.SIBOAC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TESTIGOXBOLETA
{

    public string tipo_ide { get; set; }

    public string identificacion { get; set; }

    public string fuente { get; set; }

    public int serie { get; set; }

    public decimal numero { get; set; }

}

}
