//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposPorDocumento
    {
        public string CodigoTipoDocumento { get; set; }
        public string CodigoTipoDeIdentificacion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaDeInicio { get; set; }
        public Nullable<System.DateTime> FechaDeFin { get; set; }

        public string DescripcionCodigoTipoDocumento
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                if (CodigoTipoDocumento != "")
                {
                    TipoDeDocumento tipoDoc = db.TIPODOCUMENTO.Find(CodigoTipoDocumento);
                    if (tipoDoc.Id.Trim() == CodigoTipoDocumento.Trim())
                    {
                        return Descripcion = tipoDoc.Descripcion;
                    }
                }
                return Descripcion;
            }
        }

        public string DescripcionCodigoTipoDeIdentificacion
        {
            get
            {
                string Descripcion = "";
                PC_HH_AndroidEntities db = new PC_HH_AndroidEntities();
                if (CodigoTipoDocumento != "")
                {
                    TipoDeIdentificacion tipoDoc = db.TIPO_IDENTIFICACION.Find(CodigoTipoDeIdentificacion);
                    if (tipoDoc.Id.Trim() == CodigoTipoDeIdentificacion.Trim())
                    {
                        return Descripcion = tipoDoc.Descripcion;
                    }
                }
                return Descripcion;
            }
        }

    }
}
