//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TipoVehiculoPorCodigoPorClase
    {
        [DisplayName("Código tipos vehiculos")]
        [Required(ErrorMessage = "El código es obligatorio")]
        public int CodigoTiposVehiculos { get; set; }

        [DisplayName("Código clase placa")]
        [Required(ErrorMessage = "El código es obligatorio")]
        [StringLength(3, ErrorMessage = "El codigo no debe ser mayor a 3 caracter.")]
        public string CodigoClasePlaca { get; set; }

        [DisplayName("Código Placa")]
        [Required(ErrorMessage = "El código es obligatorio")]
        [StringLength(3, ErrorMessage = "El codigo no debe ser mayor a 3 caracter.")]
        public string CodigoCodigoPlaca { get; set; }

        [DisplayName("Código Tipo Veh.")]
        [Required(ErrorMessage = "El código es obligatorio")]
        public int CodigoTipoVeh { get; set; }

        [DisplayName("Estado")]
        [StringLength(1, ErrorMessage = "El estado no debe ser mayor a 1 caracter.")]
        [Required(ErrorMessage = "El estado es obligatorio")]
        public string Estado { get; set; }

        [DisplayName("Fecha de inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "La fecha de inicio es obligatoria")]
        public Nullable<System.DateTime> FechaDeInicio { get; set; }

        [DisplayName("Fecha de fin")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "La fecha de fin es obligatoria")]
        public Nullable<System.DateTime> FechaDeFin { get; set; }

        [DisplayName("Descripción")]
        public string DescripcionCodigoTiposVehiculos
        {
            get; set;
        }
        [DisplayName("Descripción")]
        public string DescripcionCodigoTipoVeh
        {
            get; set;
        }
    }
}
