//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadesDeAlcohol
    {
        public string Id { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public System.DateTime FechaDeFin { get; set; }
    }
}
