//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSIBOAC
    {
        public int Id { get; set; }
        public string CodigoUsuario { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public Nullable<System.DateTime> FechaDeUltimoCambio { get; set; }
    }
}
