//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosevi.SIBOAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public string clase { get; set; }
        public string codigo { get; set; }
        public string placa { get; set; }
        public string marca { get; set; }
        public Nullable<int> tipo_carroceria { get; set; }
        public string tipo_ide_dueño { get; set; }
        public string identificacion_dueño { get; set; }
        public string nombre_dueño { get; set; }
        public string numero_vin { get; set; }
        public string direccion { get; set; }
        public string seguro { get; set; }
        public string rev_tecnica { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<int> codveh { get; set; }
        public decimal NumeroBoleta { get; set; }
        public int Serie { get; set; }
    }
}
